language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_script:
  - cp .env.testing .env
  - composer self-update
  - composer install  --prefer-dist --no-interaction --dev

script:
  - vendor/bin/codecept run

